package:
  name: dfcleanser
  version: "0.0.58"

source:
  git_rev: 0.0.58
  git_url: https://github.com/RickKrasinski/dfcleanser.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - dfcleanser

about:
  home: https://github.com/RickKrasinski/dfcleanser
  license: BSD
  license_file: LICENSE
