package:
  name: dfcleanser
  version: "1.0.0"

source:
  git_rev: 1.0.0
  git_url: https://github.com/RickKrasinski/dfcleanser.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - dfcleanser

about:
  home: https://github.com/RickKrasinski/dfcleanser
  license: BSD
  license_file: LICENSE.md
